version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/decamoond?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_DATABASE=decamoond
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
